version: '3.4'

services:
  logservice:
    image: logservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 7060:7060
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
