version: '3.4'

services:
  authservice:
    container_name: authservice
    image: authservice
    build:
      network: host
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      ACCESS_TOKEN_SECRET: e573eef32ee554ad4e05682c8acc621176707 80e6d21545dd137ce1b43da9e897c92c5eecb0 d766cb52e530e1d176a0ec99767b33ba98d393 313e2228ce1d92b
    ports:
      - 7070:7070
    restart: always

  logservice:
    container_name: logservice
    image: logservice
    build:
      network: host
      context: ../log-service
      dockerfile: ../log-service/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 7060:7060
    restart: always

volumes:
  data: 
